Creation d'une serie!

In [6]:
import pandas as pd
import numpy as np

In [4]:
s = pd.Series([1,2,3,4], index=['a','b','c','d'])
s

a    1
b    2
c    3
d    4
dtype: int64

In [5]:
s.index

Index(['a', 'b', 'c', 'd'], dtype='object')

In [6]:
s.values

array([1, 2, 3, 4], dtype=int64)

Pour afficher les index et les valeurs

In [7]:
s['b']

2

In [8]:
s[-4:-1]

a    1
b    2
c    3
dtype: int64

In [9]:
s[['a','b']].values

array([1, 2], dtype=int64)

In [10]:
s[0]=100
s

C:\Users\hp 830 G5\AppData\Local\Temp\ipykernel_12168\430204223.py:1: FutureWarning: Series.__setitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To set a value by position, use `ser.iloc[pos] = value`
  s[0]=100


a    100
b      2
c      3
d      4
dtype: int64

In [11]:
s['b']=50
s

a    100
b     50
c      3
d      4
dtype: int64

Pour changer les valeur avec value et index

s[s>8]

In [12]:
s[s>8]

a    100
b     50
dtype: int64

In [13]:
serd= pd.Series([1,0,2,1,2,3], index=['white','white','blue','green','green','yellow'])

In [14]:
serd

white     1
white     0
blue      2
green     1
green     2
yellow    3
dtype: int64

In [15]:
serd.unique()

array([1, 0, 2, 3], dtype=int64)

serd.value_counts() retourne cmbien de fois q'un nmbr est apparu

In [16]:
serd.value_counts()

1    2
2    2
0    1
3    1
Name: count, dtype: int64

Pas pratique

In [17]:
serd.isin([0,3])

white     False
white      True
blue      False
green     False
green     False
yellow     True
dtype: bool

In [18]:
serd[serd.isin([0,3])]

white     0
yellow    3
dtype: int64

In [8]:
s2 = pd.Series([5, -3, np.NaN, 14])
s2

0     5.0
1    -3.0
2     NaN
3    14.0
dtype: float64

Pas pratique

In [9]:
s2.notnull()

0     True
1     True
2    False
3     True
dtype: bool

Pas pratique aussi

In [22]:
s2.isnull()

0    False
1    False
2     True
3    False
dtype: bool

Plus pratique

In [10]:
s2[s2.isnull()]

2   NaN
dtype: float64

In [24]:
s2[s2.notnull()]

0     5.0
1    -3.0
3    14.0
dtype: float64

Creation avec une dictionnaire

In [11]:
mydict= {'red': 2000, 'blue': 1000, 'yellow': 500, 'orange': 1000}

In [12]:
myseries = pd.Series(mydict)
myseries

red       2000
blue      1000
yellow     500
orange    1000
dtype: int64

In [13]:
mydict2 = {'red':400,'yellow':1000,'black':700}

In [28]:
myserises2 = pd.Series(mydict2)
myserises2

red        400
yellow    1000
black      700
dtype: int64

In [14]:
myseries + myserises2

NameError: name 'myserises2' is not defined

EXO

In [15]:
S1=pd.Series(['white','blue','red','gry'])
S1

0    white
1     blue
2      red
3      gry
dtype: object

In [16]:
S2 = {100 : 1, 200 : 2, 300 : 3, 400 : 4}

In [17]:
myserie2 = pd.Series(S2)
myserie2

100    1
200    2
300    3
400    4
dtype: int64

In [18]:
S1[3]

'gry'

In [8]:
a = int(input("veillez entrer une valeur : "))
S1[a]